apiVersion: v1
kind: Service
metadata:
  labels:
    app: openldap
  name: openldap
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 1389-tcp
    port: 1389
    protocol: TCP
    targetPort: 1389
  - name: 1636-tcp
    port: 1636
    protocol: TCP
    targetPort: 1636
  selector:
    app: openldap
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
