kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: openldap-okd
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: 'openldap-okd:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM docker.io/bitnamilegacy/openldap

      USER root

      RUN setcap -r /opt/bitnami/openldap/sbin/slapd

      USER 1001
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: docker.io/bitnamilegacy/openldap
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ImageChange
    - type: ConfigChange
status: {}
